### ISSUE TITLE
build is 'passing' but binary fails: `exec format error`

### ISSUE THREAD

**Issue by bcdady** [corneliusweig/ketall#122]
**Describe the bug**
Following the steps from [Installation - OSX](https://github.com/corneliusweig/ketall#osx) and then running `ketall` results in the following error message: `exec format error: ketall`

**To Reproduce**
1. curl -Lo ketall.gz https://github.com/corneliusweig/ketall/releases/download/v1.3.6/ketall-amd64-darwin.tar.gz
2. gunzip ketall.gz
3. chmod +x ketall
4. mv ketall $GOPATH/bin/
5. 4. See error

**Expected behavior**
ketall should function as designed, such as demonstrated here: [Demo](https://github.com/corneliusweig/ketall#demo)

**Desktop (please complete the following information):**
 - output of `ketall version --full`: n/a
 - OS: macOS 11.1
 - shell: zsh 5.8 (x86_64-apple-darwin20.0)

**Additional context**
I confirmed the same symptoms with [v1.3.5](https://github.com/corneliusweig/ketall/releases/tag/v1.3.5) and [v1.3.4](https://github.com/corneliusweig/ketall/releases/tag/v1.3.5). I even tried to make/build locally, and still got the same error

**Comment by corneliusweig** [comment]
Sorry this does not work. I believe this might have something to do with https://github.com/upx/upx/issues/222.
Have you tried if a build without upx compression works for you?

**Comment by renaudguerin** [comment]
I can confirm there's an issue with the UPX binary at [https://github.com/corneliusweig/ketall/releases/download/v1.3.6/ketall-amd64-darwin.tar.gz](https://github.com/corneliusweig/ketall/releases/download/v1.3.6/ketall-amd64-darwin.tar.gz)

Big Sur 11.1 (Intel). ketall installed via krew (itself installed via Homebrew)
Any invocation (standalone or via kubectl) immediately results in `Killed: 9`

After Googling for similar issues it seemed UPX could be the culprit.
Installed UPX 3.96, uncompressed ketall with `upx -d ~/.krew/store/get-all/v1.3.6/get-all-amd64-darwin`: it works
Recompressed with this UPX version `upx -9 ~/.krew/store/get-all/v1.3.6/get-all-amd64-darwin`: still working.

**Comment by pgdagenais** [comment]
Thanks @renaudguerin I had the same issue and I was also wondering.

Had the same setup than you and was able to fix it with the `upx` command you provided.

Thank you very much!
