### ISSUE TITLE
How to delete resources

### ISSUE THREAD

**Issue by varac** [corneliusweig/ketall#146]
**Is your feature request related to a problem? Please describe.**

I'd like to delete all resources found by ketall.

**Describe the solution you'd like**

I can think of 2 solutions:

1. Implement a `--delete` flag to delete all matching resources
2. Create an output that can get piped into `kubectl delete` i.e. This would be more generic, since you could then also apply other actions than `delete`.

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by corneliusweig** [comment]
Doesn't that work already?

```sh
ketall -o name | kubectl delete
```
