### ISSUE TITLE
Support label selectors

### ISSUE THREAD

**Issue by reegnz** [corneliusweig/ketall#23]
**Is your feature request related to a problem? Please describe.**
I want to get all resources limited by a specific label selector.

**Describe the solution you'd like**
It would be great if ketall would support the "--selector" flag just as kubectl get does.

**Describe alternatives you've considered**
My alternative is to use "kubectl get" for each api-resource.

**Additional context**
Some of the kubernetes resources I create with terraform and label them with a custom label, eg. "k8s.example.com/terraform=owned". I want to collect all resources in the cluster that I have created with terraform by using a label selector.

**Comment by corneliusweig** [comment]
@reegnz Thanks for reporting this. This is definitely something `ketall` should be able to.

**Comment by reegnz** [comment]
Cool, you're awesome!
