### ISSUE TITLE
maybe exclude event.events.k8s.io by default?

### ISSUE THREAD

**Issue by ahmetb** [corneliusweig/ketall#4]
I can hardly think anyone would actually want to get all events (and similar status objects). The output is much more useful when I run `get-all | grep -v ^event`.

Maybe exclude `events/*` and `event.events.k8s.io/*` by default and offer an `--include-events` flag?

**Comment by corneliusweig** [comment]
That does make sense. However, I'm thinking about a slightly more general approach: instead of providing a dedicated flag for this, there could be an `--exclude` flag for resources that should not be considered. If it defaults to `events`, the result will be the same.

**Comment by ahmetb** [comment]
Yeah that sounds pretty cool. For some reasons I get two kinds of event objects in my output, I dunno why.

**Comment by corneliusweig** [comment]
Yes, me too. Those events differ by their api group. Same goes for deployments. I get some with `deployment.apps` and `deployment.extensions`. My assumption is that this has to do with old and new apiVersions coexisting (and probably the one is internally mapped to the other).
I wouldn't want to hide that away though.
