### ISSUE TITLE
Add option to skip failed GETs

### ISSUE THREAD

**Issue by ahmetb** [corneliusweig/ketall#41]
I get error

> 
> `$ kubectl get-all`
> `FATA[0001] fetch available group resources: get preferred resources: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

Apparently this can sometimes happen with metrics-server scraping node metrics.

A --skip-failed option (maybe shows warnings to stderr at the end), could help.

**Comment by corneliusweig** [comment]
Sorry for my :snail: response. This makes absolute sense.

In fact, I'm thinking that the best approach would be to make this the default and just show a warning for all failed resources.
