### ISSUE TITLE
Should we exclude podmetrics by default?

### ISSUE THREAD

**Issue by Aracki** [corneliusweig/ketall#50]
Think about `podmetrics.metrics.k8s.io` to be excluded by default together with `events`. It is totally unuseful resource which will be listed all the time.

This is especially ruining the output when using `--since` flag.

**Comment by corneliusweig** [comment]
Yeah, makes sense. Do you want to take a stab at it? See [CONTRIBUTING](https://github.com/corneliusweig/ketall/blob/master/CONTRIBUTING.md#pull-request-checklist) if you want to go ahead.

**Comment by Aracki** [comment]
It was really fun to create this PR #51. Please review when have time! @corneliusweig
