### ISSUE TITLE
Ketall yaml output is inconsistent with k8s standard

### ISSUE THREAD

**Issue by corneliusweig** [corneliusweig/ketall#61]
Apparently, ketall yaml list formatting is inconsistent with standard k8s output. This forces other plugins to work around:

https://github.com/nathforge/kubectl-split-yaml/blob/f1731237efcf876af9af31f6e6df350b70885c2b/internal/walkresources/walkresources.go#L97-L118

> kubectl would represent two items as:
	//     apiVersion: v1
	//     kind: List
	//     items:
	//     - AAA
	//     - BBB
	//
	// ketall represents the same two items as:
	//     apiVersion: v1
	//     kind: List
	//     items:
	//     - items:
	//       - AAA
	//       - BBB
	//
	// Notice the extra items objects with no apiVersion or kind.

It would be better to solve this in `ketall` and be fully compliant.

cc @nathforge

**Comment by nathforge** [comment]
Thanks @corneliusweig! Will try to pick this up if nobody gets there first - here's a reproduction:

```
$ kubectl create configmap ketall-items-test
$ kubectl label configmap ketall-items-test demo=demo
```
```
$ kubectl get configmap -l demo=demo -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata: [...]
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
```
$ kubectl get-all -l demo=demo -o yaml
apiVersion: v1
items:
- items:
  - apiVersion: v1
    kind: ConfigMap
    metadata: [...]
kind: List
metadata: {}
```
