### ISSUE TITLE
Plugin cannot be used as 'kubectl get-all' due to naming conventions

### ISSUE THREAD

**Issue by antoineco** [corneliusweig/ketall#76]
**Describe the bug**

According to https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#naming-a-plugin, dashes in the plugin name are used to delimit _subcommands_. However, because `get` is a built-in `kubectl` command, naming the plugin executable `kubectl-get-all` does not override `kubectl get all`, and `kubectl get-all` is ignored altogether.

> For example, adding a subcommand `kubectl create foo` by naming your plugin `kubectl-create-foo` will cause that plugin to be ignored.
>
> -- https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#limitations

**To Reproduce**

1. Symlink the plugin executable in 2 different manners:

    ```sh
    kubectl-get-all_v1.3.2_linux-amd64
    kubectl-get-all -> kubectl-get-all_v1.3.2_linux-amd64
    kubectl-getall -> kubectl-get-all_v1.3.2_linux-amd64
    ```

2. Run `kubectl get-all` and `kubectl getall`

3. Observe that `kubectl get-all` returns the error `Error: unknown command "get-all" for "kubectl"`, while  `kubectl getall` succeeds.

**Expected behavior**

This repo should change all mentions to `kubectl-get-all`, including in the release artifacts' names.

**Desktop**
 - kubectl `v1.16.6`
 - OS: Linux

**Comment by corneliusweig** [comment]
Thanks for reporting this. Plugin names with underscores are perfectly ok, see https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#names-with-dashes-and-underscores.

For simpler installation of plugins, I'd recommend to use https://krew.sigs.k8s.io/, which installs plugins with the right name.

**Comment by antoineco** [comment]
Same result with Krew. The problem is not the dash, the problem is that the name of the plugin clashes with the built-in command `get`. It used to work (I've been using the plugin for a while), but not anymore. Everything is explained above.

The repo is currently full of references to `kubectl get-all`, but that command is rejected by `kubectl` with the aforementioned error.

I would appreciate if you could give it a second look, this is a genuine and confusing problem.

**Comment by antoineco** [comment]
Ahhhh, there you go, `kubectl-get_all`, not `kubectl-get-all`. Thanks for the pointer!
