### ISSUE TITLE
ketall with EKS and aws-iam-authenticator leads to socket exhaustion

### ISSUE THREAD

**Issue by jebeaudet** [corneliusweig/ketall#83]
**Describe the bug**
Using ketall with an EKS setup and https://github.com/kubernetes-sigs/aws-iam-authenticator leads to many aws client created and eventually socket descriptor exhaustion.

**To Reproduce**
1. Have an EKS + IAM auth setup
2. Run kubectl get-all
3. You'll see a bunch of messages like (with the client count incrementing): 
```W0828 08:26:24.925622   16543 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1831 clients constructed calling "aws"```
4. Then error messages like : 
```WARN[0035] Cannot fetch: Get https://REDACTED.gr7.us-east-1.eks.amazonaws.com/apis/extensions/v1beta1/replicasets: dial tcp 10.6.4.45:443: socket: too many open files```

**Expected behavior**
The plugin should reuse the aws instance? Not so sure where the problem lies TBH, feel free to redirect me!

**Desktop (please complete the following information):**
 - get-all  v1.3.2
 - OS: Ubuntu 18.04

**Additional context**
Related issue : https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/308
Might help others too if I link https://github.com/kubernetes/kubectl/issues/151 (that's how I ended up finding your plugin)

**Comment by corneliusweig** [comment]
I think the problem is here: 
https://github.com/corneliusweig/ketall/blob/1649671375dc29fc4a60b86b05122be76f82ea45/internal/client/client.go#L184-L192

Apparently, this is not rate-limited and an arbitrary number of connections is opened. I'll try to get to it, but it might take some time.
