### ISSUE TITLE
No resources returned in v1.3.4

### ISSUE THREAD

**Issue by dean-alphafx** [corneliusweig/ketall#93]
**Describe the bug**
No resources are being returned in the latest version of the krew plugin.

**To Reproduce**
1. kubectl get-all -n bar
2. See error:
`DEBU[0000] Set log-level to debug
DEBU[0001] Resources to fetch: []
DEBU[0001] Initial fetchResourcesBulk done (0s)
DEBU[0001] Fetch resources incrementally
DEBU[0001] Requests done (elapsed 0s)
WARN[0001] No resources found, are you authorized? Try to narrow the scope with --namespace.
FATA[0001] no resources found`

**Expected behavior**
I expected too see the same resources I could in v1.3.2

**Screenshots**
<img width="866" alt="image" src="https://user-images.githubusercontent.com/65293263/93106772-a1571980-f6a8-11ea-9d38-10e205b5c550.png">

**Desktop (please complete the following information):**
 - output of `ketall version --full`:
> ketall:     v1.3.4
> platform:   darwin/amd64
> git commit: 071f5c7ec0f520ab9be82529c08e83fc726b4910
> build date: 2020-09-04T23:14:49Z
> go version: go1.15
> compiler:   gc
 - OS: MacOS
 - Browser: Firefox
 - Version 1.3.4

**Additional context**
Exact same command and kubectl version worked fine for version 1.3.2, seems to be a bug.

**Comment by corneliusweig** [comment]
Can you also share your kubernetes version? `kubectl version`
And are you running a standard k8s distribution? 

I bumped the k8s version in 1.3.3 and maybe that creates some incompatibilities.

**Comment by dean-alphafx** [comment]
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by busser** [comment]
v1.3.3 works for me but not v1.3.4.

I believe a previous commit broke `ketall` though: https://github.com/corneliusweig/ketall/commit/93a2c9fab577b7f1beb6a32b31606ed3ab6cbfa9

Specifically, all booleans in the scope logic were flipped except this one: https://github.com/corneliusweig/ketall/commit/93a2c9fab577b7f1beb6a32b31606ed3ab6cbfa9#diff-2c846caea57b2b1d6e49c6417f337625R214

I've opened a pull request with a fix: https://github.com/corneliusweig/ketall/pull/98

**Comment by dean-alphafx** [comment]
Thanks, latest version is now working for me 👍

**Comment by corneliusweig** [comment]
The praise goes to @busser who looked into this.
